config/routes.rb
Rails.application.routes.draw do
  get 'pharmacies/index'
  get 'pharmacies/show'
  root to: 'pages#home'
  resources :prescriptions, only: [:index, :new, :create, :show, :destroy] do

    get 'show_before_order', to: 'prescriptions#show_before_order'

    get 'show_after_order', to: 'prescriptions#show_after_order'

    resources :orders, only: [:index, :new, :create, :destroy, :show]

  end

  resources :orders, only: [:index, :show]


  get 'welcome', to: "pages#welcome"
  get 'delivery', to: "pages#delivery"

  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :orders_prescriptions, dependent: :destroy
  has_many :prescriptions, through: :orders_prescriptions

  belongs_to :pharmacie, optional: true
end

app/models/orders_prescription.rb
class OrdersPrescription < ApplicationRecord
  belongs_to :order
  belongs_to :prescription
end

app/models/pharmacie.rb
class Pharmacie < ApplicationRecord
  geocoded_by :address
  has_many :orders
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/prescription.rb
class Prescription < ApplicationRecord
  belongs_to :user
  has_many :orders_prescriptions
  has_many :orders, through: :orders_prescriptions

  mount_uploader :image, ImageUploader
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :prescriptions
  has_many :orders
  mount_uploader :avatar, ImageUploader
  mount_uploader :id_card, ImageUploader
  mount_uploader :social_security, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar, :street_name, :zip_code, :city, :phone_number, :id_card, :social_security])

    # For additional in app/views/devise/registrations/edit.html.erb
    #devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end


  def after_sign_in_path_for(resource)
    welcome_path
  end


  def after_sign_up_path_for(resource)
    welcome_path
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user: current_user)
  end

  def new
    @prescription = Prescription.find(params[:prescription_id])
    @order = Order.new
  end

  def create
    @prescription = Prescription.find(params[:prescription_id])
    @order = Order.new(order_params)
    @order.user = current_user
    @order.order_status = "pending"
    @order.order_date = Date.today
    if @order.save
      OrdersPrescription.create!(prescription_id: @prescription.id, order_id: @order.id)
      redirect_to prescription_show_after_order_path
    else
      render :new
    end
    session[:counter] = nil
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy


    @prescription = Prescription.find(params[:prescription_id])
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to prescription_orders_path(@prescription)

  end


  # def edit
  #    @order = Order.find(params[:id])
  # end

  #   def update
  #   @order = Order.find(params[:id])
  #   @order.update(order_params)
  #   redirect_to  prescription_orders_path

  #   end

  private

  def order_params
    params.require(:order).permit(:street_name, :zip_code, :city)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end


  def welcome
    @prescription = Prescription.new
  end


  def order_placement

  end

  def order_placement_2
    @order= Order.new
  end

  def order_placement_3
  end

  def delivery
  end

end

app/controllers/pharmacies_controller.rb
class PharmaciesController < ApplicationController
  def index
    @pharmacies = Pharmacie.where.not(latitude: nil, longitude: nil)

    @markers = @pharmacies.map do |pharmacie|
      {
        lat: pharmacie.latitude,
        lng: pharmacie.longitude
      }
    end
  end

  def show

  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  def index
    @prescriptions = Prescription.where(user: current_user)
  end

  def create
    @prescription = Prescription.new(prescription_params)
    @prescription.user = current_user
    if @prescription.save
    redirect_to prescription_show_before_order_path(@prescription)
    else
      render :new
    end
  end

  def new
    @prescription = Prescription.new
  end

  def show
    @prescription = Prescription.find(params[:id])
  end

  def show_before_order
    @prescription = Prescription.find(params[:prescription_id])
  end

  def show_after_order

    @prescription = Prescription.find(params[:prescription_id])

    session[:counter].present? ? simul_validation_pharm : counter

  end

  def destroy
    @prescription = Prescription.find(params[:id])
    @prescription.destroy
    redirect_to prescriptions_path
  end

  private

  def counter
    session[:counter] = 1
  end

  def simul_validation_pharm
    @order = Order.last
    @order.order_status = "Accepté"

    @pharmacie = Pharmacie.find(1)
    @order.pharmacie = @pharmacie

    @order.save
    set_marcker
  end

  def set_marcker

    @geocoded_adress = @pharmacie.geocode
      @markers = []
      @marker =
        {
          lat: @geocoded_adress.first,
          lng: @geocoded_adress.second
        }
         @markers << @marker
         session[:counter] = nil
  end

  def prescription_params
    params.require(:prescription).permit(:image, :image_cache, :prescription_name, :prescription_start_date, :prescription_expiry_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
     content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
     meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
     # little twist to make it work equally with an asset or a url
     meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,500i,600,600i,700,700i,800&display=swap" rel="stylesheet">

    <title><%=meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= favicon_link_tag %>


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<div class="orders-container">
  <div class="orders-header">
    <div class="text-my-orders">
      <%= link_to welcome_path do%>
      <i class="fas fa-chevron-left chevron-style"></i>
      <%end%>
      <h2 class="h2-style">Mes commandes</h2>
    </div>
  </div>
</div>
<div class="orders-body">
  <% @orders.each do |order| %>
  <div class="card-category-orders">

    <div class="colored-hover">
      <h6 class="card-subtitle mb-2 text-muted">Commande<br> #<%= order.order_number %></h6>
      <h6 class="card-subtitle mb-2 text-muted"><%= order.order_status %></h6>
    </div>
    <div class="show-delete d-flex">
      <div class="show-delete-address d-flex">
        <%= image_tag ("process.png"), class: "process-logo", style: "height: 95%;" %>
        <div>
          <p class="card-text"><%= order&.pharmacie&.address || "En attente de la pharmacie" %></p>
          <p class="card-text"><%= order.street_name %> </p>
        </div>
      </div>
      <div class="d-flex align-items-center justify-content-between">
        <div>
        <%= link_to order_path(order) do %>
        <%= image_tag ("see-more.svg"), class: "see-more-logo" %>
        <% end %>
        <%= link_to prescription_order_path(order.prescriptions.first, order.id), method: :delete do %>
        <%= image_tag ("rubbish-bin.svg"), class: "rubbish-bin-logo" %>
        <% end %>
        </div>
      <p class="m-0">2.5€</p>
      </div>
    </div>

  </div>
  <% end %>
</div>
<div class="d-flex align-items-end">
  <%= render 'shared/footer' %>
</div>

app/views/orders/new.html.erb
<div class="address-contaier">
  <div class="address-header">
    <div class="placeaddress d-flex justify-content-start">
      <%= link_to welcome_path do%>
      <%= image_tag ("close.png"), class: "arrow-address" %>
      <%end%>
      <h2 class="text-header-address">Faire une commande</h2>
    </div>
    <div class="address-steps">
      <%= image_tag ("2.png"), class: "steps-address" %>
    </div>
  </div>

    <div class="address-body">
      <p class="addressbody-text">Votre adresse de livraison: </p>
      <div class="white-container-address">
        <%= simple_form_for [@prescription, @order] do |f| %>
          <%= f.input :street_name, label: "Adresse", input_html: { value: current_user.street_name, class: "street_name" } %>
          <%= f.input :zip_code, label: "Code Postal", input_html: { value: current_user.zip_code, class: "zip_code" } %>
          <%= f.input :city, label: "Ville", input_html: { value: current_user.city, class: "cityname_input" }%>

        <div class="select-this-address">
          <button type="submit" class="selectaddr">
          <%= image_tag ("next.svg"), class: "nexttwo" %>
          </button>
        </div>
      </div>
    </div>
    <div class="white-footer-address">
      <% end %>
    </div>
  </div>

app/views/orders/show.html.erb
<div class="order-container">

  <!-- <i class="fas fa-circle circle-style"></i> -->
  <div class="order-header">

    <div class="text-show-order">
      <%= link_to prescription_orders_path do %>
      <i class="fas fa-chevron-left chevron-style"></i>
      <% end %>
      <h2 class="h2-style">Ma commande #<%= @order.id %></h2>

    </div>
  </div>
</div>

<div class="order">
<div class="show-prescription-name">Commande # <%= @order.id %></div>

<div class="show-prescription-date">Date de la commande : <%= @order.order_date %></div>

<div class="show-prescription-date">Status : <%= @order.order_status %></div>

<div class="show-prescription-date">Adresse de livraison : </div>
<div class="show-prescription-date"><%= @order.street_name %></div>
<div class="show-prescription-date"><%= @order.zip_code %> <%= @order.city %></div>
</div>
<%= render 'shared/footer' %>

app/views/pages/delivery.html.erb
<%= link_to welcome_path do %>
<%= image_tag ("cross-exit.png"), class: "cross-exit" %>
<% end %>
<div class="background-stuff">
  <h2 class="titledelivery">Merci pour votre commande</h2>
  <div class="deliverycontainer">
    <div class="car-wrapper">
      <div class="car-container">
        <div class="car-wrapper_inner">
          <div class="car_outter">
            <div class="car">
              <div class="body">
                <div></div>
              </div>
              <div class="decos">
                <div class="line-bot"></div>
                <div class="door">
                  <div class="handle"></div>
                  <div class="bottom"></div>
                </div>
                <div class="window"></div>
                <div class="light"></div>
                <div class="light-front"></div>
              </div>
              <div>
                <div class="wheel"></div>
                <div class="wheel"></div>
              </div>
              <div class="wind">
                <div class="p p1"></div>
                <div class="p p2"></div>
                <div class="p p3"></div>
                <div class="p p4"></div>
                <div class="p p5"></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="ground">
    <h2 class="textdelivery">Livraison en cours</h2>
    <p class="getwell">Bon rétablissement !</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="welcome-page">
  <div class="welcome-centered">
    <%= image_tag "logo-cura.png", class: "logo-cura" %>
    <p class="tagline">Medicine at your doorstep</p>
    <div class="links-emplacement" >
      <div class="center-xy">
        <em> <p class ="slidetext">Slide to open</p></em>
        <input type="range" value="0" class="pullee"   target="_blank" />
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

setTimeout(function() {
const links = document.querySelector(".links-emplacement");
  links.style.display = "block";

}

  ,1000);

</script>


<!--<%= link_to  "Start", new_user_session_path, class: "btn-white" %>

      <%= link_to  "Sign out", destroy_user_session_path, method: :delete, class: "btn-white" %>
      <%= link_to  ("Not a member?<strong> Sign up</strong>").html_safe, new_user_registration_path, class: "signup-link" %> -->

app/views/pages/order_placement.html.erb
<div class="order-contaier">
  <div class="order-header">
    <div class="placeorder d-flex justify-content-start">
      <%= link_to welcome_path do%>
      <%= image_tag ("left-arrow.png"), class: "arrow-order" %>
      <%end%>
      <h2 class="text-header-order">Placing an order</h2>
    </div>
    <div class="order-steps">
      <%= image_tag ("1.png"), class: "steps-order" %>
    </div>
  </div>
  <div class="order-body">
    <div class="white-container">
      <p class="orderbody-text">Your prescription</p>
      <div class="links-scan d-flex">
        <%= link_to welcome_path do%>
        <div class="rescan-div d-flex">
          <%= image_tag ("reload.png"), class: "rescan-photo" %>
          <p class="rescan">Rescan</p>
        </div>
        <%end%>
        <div class="add-div">
          <%= link_to welcome_path do%>
          <p class="text-scan">+ Add another product</p>
          <%end%>
        </div>
      </div>
      <div class="image-uploaded">
        <%= image_tag("scan.png") %>
      </div>
      <div class="saveforlater">
        <%= link_to welcome_path do%> <p class="savetext">Save in my prescriptions</p><%end%>
      </div>
      <div class="white-footer">
        <%= link_to order_placement_2_path do%>
        <%= image_tag ("right.png"), class: "next-order" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/pharmacies/index.html.erb
<div class="pharmacies-container">

  <div class="pharmacies-header">
    <div class="text-my-pharmacies">
      <%= link_to welcome_path do%>
      <i class="fas fa-chevron-left chevron-style"></i>
      <%end%>
      <h2 class="h2-style">Pharmacies</h2>
    </div>
  </div>
</div>

<div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

<div class="pharmacies-body">
  <% @pharmacies.each do |pharmacie| %>
  <div class="card-category">
    <div class="pharmacie-name"><%= pharmacie.name %></div>
    <div class="pharmacie-address">Address : <%= pharmacie.address %></div>
     <div class="pharmacie-phone-number">Phone : <%= pharmacie.phone_number %></div>
    <div class="show-delete">
      </button>
    </div>
  </div>
  <% end %>
</div>

app/views/pharmacies/show.html.erb
<h1>Pharmacies#show</h1>
<p>Find me in app/views/pharmacies/show.html.erb</p>

app/views/prescriptions/index.html.erb
<div class="prescriptions-container">

  <div class="prescriptions-header">
    <div class="text-my-prescriptions">
      <%= link_to welcome_path do%>
      <i class="fas fa-chevron-left chevron-style"></i>
      <%end%>
      <h2 class="h2-style"> Mes Prescriptions</h2>
    </div>
  </div>
</div>
<div class="prescriptions-body">
  <% @prescriptions.each do |prescription| %>
  <div class="card-category">
    <div class="prescription-name"><%= prescription.prescription_name %></div>
    <div class="prescription-date">Début de la prescrition : <%= prescription.prescription_start_date %></div>
    <div class="prescription-date">Fin de la prescription : <%= prescription.prescription_expiry_date %></div>
    <div class="show-delete">
      <button type="button" class="btn btn-outline-light btn-outline-style-show-index" ><%= link_to "Afficher", prescription_path(prescription) %></button>
      <button type="button" class="btn btn-outline-light btn-outline-style-delete-index" ><%= link_to "Suprimer", prescription_path(prescription.id), method: :delete %>
      </button>
    </div>
  </div>
  <% end %>

</div>
<%= render 'shared/footer' %>

app/views/prescriptions/show.html.erb
<div class="prescriptions-container">

  <!-- <i class="fas fa-circle circle-style"></i> -->
  <div class="prescriptions-header">

    <div class="text-show-prescriptions">
      <%= link_to prescriptions_path do%>
      <i class="fas fa-chevron-left chevron-style"></i>
      <%end%>
      <h2 class="h2-style"><%= @prescription.prescription_name %></h2>

    </div>
  </div>
</div>
<div class="prescription">
  <div class="img-card"><%= cl_image_tag @prescription.image, :width=>250, :height=>290 %></div>
  <div class="show-prescription-name">Validité de la prescription :</div>
  <div class="show-prescription-date">Date de la prescription : <%= @prescription.prescription_start_date %></div>
  <div class="show-prescription-date">Fin de la prescription : <%= @prescription.prescription_expiry_date %></div>
  <div class="make-an-order-and-delete">
    <button type="button" class="btn btn-outline-light btn-outline-style-make-an-order-show" ><%= link_to "Passer commande", new_prescription_order_path(@prescription) %></button>
    <button type="button" class="btn btn-outline-light btn-outline-style-delete-show" ><%= link_to "Supprimer", prescription_path, method: :delete %></button>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/prescriptions/show_after_order.html.erb
<div class="order-contaier">
  <div class ="body-orders-steps">
    <% if @prescription.orders.last.order_status == "pending" %>
    <div class="order-header">
      <div class="placeorder d-flex justify-content-start">
        <%= link_to welcome_path do%>
        <%= image_tag ("close.png"), class: "arrow-order" %>
        <%end%>
        <h2 class="text-header-order">Faire une commande</h2>
      </div>
      <div class="order-steps">
        <%= image_tag ("3.png"), class: "steps-order" %>
      </div>
    </div>
    <p class="textconfirmation">Suivi de votre commande</p>
    <%= image_tag ("pharmacist-prep.png") , class: "pharmacistdelivery"%>
    <div class="orderstatusone" >
      <div class="statusone d-flex justify-content-around">
        <div class="spinnerone">
          <div class="spinner-border text-primary spinner" style="width: 1.3rem; height: 1.3rem;" role="status"></div>
        </div>
        <p id ="statusonetext">Votre commande a été acceptée</p>
        <p class= "timeone"><%= Time.now %></p>
      </div>
      <div class="statustwo d-flex justify-content-around">
        <div class="spinnertwo">
          <div class="spinner-border text-primary spinner" style="width: 1.3rem; height: 1.3rem;" role="status"></div>
        </div>
        <p id="statustwotext">Préparation de votre commande</p>
        <p  class="timetwo"><%= Time.now %></p>
      </div>
      <div class="statusthree d-flex justify-content-around">
        <div class="spinnerthree">
          <div class="spinner-border text-primary spinner" style="width: 1.3rem; height: 1.3rem;" role="status"></div>
        </div>
        <p id="statusthreetext">Préparation de votre facture</p>
        <p class="timethree"><%= Time.now %></p>
      </div>
    </div>
  </div>
  <% end %>
  <% if @prescription.orders.last.order_status == "Accepté"  %>
  <div class="textdiv">
    <div>
      <h2 class ="orderstatustwo ">Détails de votre commande</h2>
      <div class="card" >
        <div class="pharmaciedetails">
          <p class="pharmacie"> Votre Pharmacie</p>
          <p class ="namepharmacie"><%= @prescription.orders.last.pharmacie.name %></p>
          <p class ="addresspharmacie"><%= @prescription.orders.last.pharmacie.address %></p>
        </div>
        <div class="mapcss">
          <div
            id="map"
            style="width: 89%;
            height: 157px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
          ></div>
        </div>
      </div>
      <div class= "orderpayment">
        <div class="cardsorder p-3 ">
          <div class="d-flex justify-content-between mb-3">
            <p><strong>Montant de l'ordonnance</strong> </p>
            <p>4.95€</p>
          </div>
          <div class="d-flex justify-content-between mb-3">
            <p><strong>Montant pris en charge</strong></p>
            <p>3.95€</p>
          </div>
          <div class="d-flex justify-content-between mb-3 border-bottom">
            <p><strong>Frais de livraison</strong></p>
            <p>1.5€</p>
          </div>
          <div class="d-flex justify-content-between mb-3 ">
            <p><strong>Total à régler</strong></p>
            <p><strong>2.5€</strong></p>
          </div>
        </div>
        <div class="buttonsorder">
          <button type="button" class="submitpopup" data-toggle="modal" data-target="#exampleModal">Payer</button>
          <button type="button" class="cancelpopup">Annuler</button>
        </div>
      </div>

      <div>
       <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" id ="popuppayment"role="document">
          <div class="modal-container">
            <div class="pop-up-header">
              <div class="modal-title" id="cameradiv">
              <p>Paiement</p>
                <form>
                 <div class="form-group">
                   <label for="formGroupExampleInput">Numéro de la carte</label>
                   <input type="text" class="form-control" id="formGroupExampleInput" placeholder="4242 4242 4242 4242"><%= image_tag ("visa-logo.jpg"), class: "img-visa"%>
                 </div>
                 <div class="form-group">
                  <label for="formGroupExampleInput2">Date d'expiration</label>
                  <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="01/21">
                 </div>
                 <div class="form-group">
                  <label for="formGroupExampleInput2">Cryptogramme</label>
                  <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="442">
                 </div>
                 <div class="form-group row">
                   <div class="col-sm-10 buttoncenter">
                    <button type="submit" class="submitpayment"><%= link_to "Valider", delivery_path, class: "validationtext" %></button>
                   </div>
                </form>
              </div>
            </div>
          </div>
        <div class="pop-up-footer">
          <button type="button"  data-dismiss="modal" class="button-pop-up"> Close</button>
        </div>
      </div>
    </div>

    <% end %>

    <script type="text/javascript">
    const spinner = document.querySelector(".spinnerone");
    if (spinner) {
    setTimeout(function() {
    spinner.innerHTML = '<%= image_tag ("check.png")%>';
    }
    ,2000);
    }
    const spinnertwo = document.querySelector(".spinnertwo");
    setTimeout(function() {
    spinnertwo.innerHTML = '<%= image_tag ("check.png")%>';
    }
    ,4500);
    const spinnerthree = document.querySelector(".spinnerthree");
    setTimeout(function() {
    spinnerthree.innerHTML = '<%= image_tag ("check.png")%>';
    }
    ,7000);
     setTimeout(function() {
     const links = document.querySelector(".timeone");
    links.style.display = "block";
    }
      ,2030);
     setTimeout(function() {
     const linkstwo = document.querySelector(".timetwo");
    linkstwo.style.display = "block";
    }
      ,4530);
     setTimeout(function() {
     const linksthree = document.querySelector(".timethree");
    linksthree.style.display = "block";
    }
      ,7030);
    </script>

app/views/prescriptions/show_before_order.html.erb
<!-- *************************placing order one***************************** -->
 <div class="order-contaier">
  <div class="order-header">
    <div class="placeorder d-flex justify-content-start">
      <%= link_to welcome_path do%>
      <%= image_tag ("close.png"), class: "arrow-order" %>
      <%end%>
      <h2 class="text-header-order">Faire une commande</h2>
    </div>
    <div class="order-steps">
      <%= image_tag ("1.png"), class: "steps-order" %>
    </div>
  </div>
  <div class="order-body">
    <div class="white-container">
      <p class="orderbody-text"> Scannez votre ordonnance</p>
      <div class="links-scan d-flex">
        <%= link_to welcome_path do%>
        <div class="rescan-div d-flex">
          <%= image_tag ("reload.png"), class: "rescan-photo" %>
          <p class="rescan">Rescanner</p>
        </div>
        <%end%>
        <div class="add-div">
          <%= link_to welcome_path do%>
          <p class="text-scan">+ Ajouter ordonnance</p>
          <%end%>
        </div>
      </div>
      <div class="image-uploaded">
        <%= cl_image_tag @prescription.image, height: 230, width: 180, crop: :fill %>
      </div>
      <!-- <div class="saveforlater">
        <%= link_to welcome_path do%> <p class="savetext">Save in my prescriptions</p><%end%>
      </div>
 -->

      <div class="white-footer">
        <%= link_to  new_prescription_order_path(@prescription) do%>
        <%= image_tag ("next.svg"), class: "nextone" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="welcome-footer-home d-flex">
     <%= link_to welcome_path do%>
    <%= image_tag ("home.png"), class: "homeicon grow " %>
    <% end %>
    <%= link_to orders_path do%>
    <%= image_tag ("orders-white.png"), class: "ordersicon grow " %>
    <% end %>
    <%= link_to prescriptions_path do%>
    <%= image_tag ("pres-white.png"), class: "presicon grow " %>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete do%>
    <%= image_tag ("logout-white.png"), class: "logicon grow " %>
    <% end %>

</div>